### ISSUE TITLE
Invariants ignored by `prove`

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/act#76] opened 2020-12-15 16:40 UTC
```
constructor of LValue
interface constructor()

creates
	uint x := 0
	uint y := 2

invariants
	x == 0
	y == 2

behaviour f of LValue
interface f()

storage
	x => 0
	y => 2
```

Also not sure what the expected behavior here is, but I get:
```
$ ./result/bin/act prove --file lvalue.act

============

Invariant "(LValue.x == 0)" of "LValue": Q.E.D
```
Shouldn't `y == 2` also be proved? Or am I missing something?

**Comment by xwvvvvwx** [comment] 2020-12-17 14:33
hmmmm I just ran this with current `master` and it seems to be proving both of them on my machine. Can you still reproduce this @leonardoalt?

```
============

Invariant "(LValue.x == 0)" of "LValue": Q.E.D ✨

============

Invariant "(LValue.y == 2)" of "LValue": Q.E.D ✨
```

**Comment by xwvvvvwx** [comment] 2020-12-18 08:49
Fixed by https://github.com/ethereum/act/pull/80

**Closed** 2020-12-18 08:49 UTC
Labels: bug
